export const ChevronRightIcon = (props) => <i {...props} className={`fal fa-chevron-right ${props.className}`}></i>;
export const ChevronLeftIcon = (props) => <i {...props} className={`fal fa-chevron-left ${props.className}`}></i>;
export const ChevronDownIcon = (props) => <i {...props} className={`fal fa-chevron-down ${props.className}`}></i>;
export const ChevronUpIcon = (props) => <i {...props} className={`fal fa-chevron-up ${props.className}`}></i>;
export const AngleDownIcon = (props) => <i {...props} className={`fal fa-angle-down ${props.className}`}></i>;
export const AngleUpIcon = (props) => <i {...props} className={`fal fa-angle-up ${props.className}`}></i>;
export const AngleLeftIcon = (props) => <i {...props} className={`fal fa-angle-left ${props.className}`}></i>;
export const AngleRightIcon = (props) => <i {...props} className={`fal fa-angle-right ${props.className}`}></i>;
export const ChevronRightLongIcon = (props) => <i {...props} className={`fal fa-long-arrow-right ${props.className}`}></i>;
export const BarsIcon = (props) => <i {...props} className={`fal fa-bars ${props.className}`}></i>;
export const TimesIcon = (props) => <i {...props} className={`fal fa-times ${props.className}`}></i>;
export const SearchIcon = (props) => <i {...props} className={`fal fa-search ${props.className}`}></i>;
export const UserIcon = (props) => <i {...props} className={`fal fa-user-alt ${props.className}`}></i>;
export const HeartIcon = (props) => <i {...props} className={`fal fa-heart ${props.className}`}></i>;
export const CartIcon = (props) => <i {...props} className={`fal fa-baby-carriage ${props.className}`}></i>;
export const PhoneIcon = (props) => <i {...props} className={`fal fa-phone-alt ${props.className}`}></i>;
export const LocationIcon = (props) => <i {...props} className={`fal fa-map-marker-alt ${props.className}`}></i>;
export const EmailIcon = (props) => <i {...props} className={`fal fa-envelope ${props.className}`}></i>;
export const StarIcon = (props) => <i {...props} className={`fas fa-star ${props.className}`}></i>;
export const FacebookIcon = (props) => <i {...props} className={`fab fa-facebook-f ${props.className}`}></i>;
export const TwitterIcon = (props) => <i {...props} className={`fab fa-twitter ${props.className}`}></i>;
export const GoogleIcon = (props) => <i {...props} className={`fab fa-google ${props.className}`}></i>;
export const HomeIcon = (props) => <i {...props} className={`fal fa-home-lg-alt ${props.className}`}></i>;
export const RepeatIcon = (props) => <i {...props} className={`fal fa-sync-alt ${props.className}`}></i>;
export const PaymentIcon = (props) => <i {...props} className={`fal fa-money-check-alt ${props.className}`}></i>;
export const HandHelpIcon = (props) => <i {...props} className={`fal fa-hands-helping ${props.className}`}></i>;
export const TruckIcon = (props) => <i {...props} className={`fal fa-truck ${props.className}`}></i>;
export const ListIcon = (props) => <i {...props} className={`fas fa-bars ${props.className}`}></i>;
export const GridIcon = (props) => <i {...props} className={`far fa-border-all ${props.className}`}></i>;
export const FilterHeroIcon = (props) => <i {...props} className={`far fa-sliders-h ${props.className}`}></i>;


// export const PlusIcon = (props) => <i {...props} className={`fal fa-plus ${props.className}`}></i>;
// export const MinusIcon = (props) => <i {...props} className={`fal fa-minus ${props.className}`}></i>;